### ISSUE TITLE
module 04 SDN Install script fails when starting SLBhostagent service

### ISSUE THREAD

**Issue by garjam73** [MicrosoftLearning/WS-013T00-Azure-Stack-HCI#4]
# Module: 004
#### Step: 07

Description of issue

OsName                                                  : Microsoft Windows Server 2019 Datacenter
OsType                                                  : WINNT
OsOperatingSystemSKU                                    : DatacenterServerEdition
OsVersion                                               : 10.0.17763

when running the scripts to deploy SDN the script fails with the following error
VERBOSE: [20201206-19:16:41] Configure and start SLB Host Agent.
VERBOSE: [20201206-19:16:41] Begin Invoke-Command output:
VERBOSE: [20201206-19:16:42] [HV1] Configuring and starting SLB host agent.
C:\Library\SDN-master\SDNExpress\scripts\SDNExpress.ps1 : Failed to start service 'Software Load Balancer Host Agent 
(SLBHostAgent)'.
At line:4 char:1
+ . "C:\Library\SDN-master\SDNExpress\scripts\SDNExpress.ps1" -Configur ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], Servi 
   ceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand

As the script fails you are unable to sucessfully complete the SND labs 

Repro steps:

1. Prepare lab with licensed 2019 Media
2. complete task 1 to build th eenvironment
3. run the scenario_Part2 script to generate the error after around 40 minutes.

**Comment by PurvesG** [comment]
There are 2 problems with the new SDNExpress scripts both in the SDNExpressModule.psm1
1.) O/S Validation fails on Evaluation version
Modify Line 2652
    # ("ServerDatacenterCor", "ServerDatacenter", "ServerAzureStackHCICor") -contains $Edition.Edition)
    ("ServerDatacenterEvalCor", "ServerDatacenterCor", "ServerDatacenter", "ServerAzureStackHCICor") -contains $Edition.Edition)

2.) slbhpconfig.xml fails to generate causing the SLBHostAgent to fail on all hosts
A fix has been submitted to the SDNExpress  GitHub but has not been merged with master
There are white spaces on several lines which cause the slbhpconfig.xml to fail to create
    github.com/.../958f16874d30e9bd9c6b018506730f7890d7d252

Until the fix is merged students must edit the SDNExpressModule.psm1 before executing Scenario_Part2.ps1

To do this locate the Expand-Archive in the Scenario_Part2.ps1 execute it then REM it out
# ~ Line 240
# Expand-Archive -Path C:\SDN-Master.zip -DestinationPath C:\Library

Then edit the sections in the  "C:\Library\SDN-master\SDNExpress\scripts\SDNExpressModule.psm1" as above

**Comment by PurvesG** [comment]
There are 2 problems with the new SDNExpress scripts both in the SDNExpressModule.psm1
1.) O/S Validation fails on Evaluation version
Modify Line 2652
    ("ServerDatacenterCor", "ServerDatacenter", "ServerAzureStackHCICor") -contains $Edition.Edition)
    ("ServerDatacenterEvalCor", "ServerDatacenterCor", "ServerDatacenter", "ServerAzureStackHCICor") -contains $Edition.Edition)

2.) slbhpconfig.xml fails to generate causing the SLBHostAgent to fail on all hosts
A fix has been submitted to the SDNExpress  GitHub but has not been merged with master
There are white spaces on several lines which cause the slbhpconfig.xml to fail to create
    github.com/.../958f16874d30e9bd9c6b018506730f7890d7d252

Until the fix is merged students must edit the SDNExpressModule.psm1 before executing Scenario_Part2.ps1

To do this locate the Expand-Archive in the Scenario_Part2.ps1 execute it then REM it out
Oround Line 240
Expand-Archive -Path C:\SDN-Master.zip -DestinationPath C:\Library

Then edit the sections in the  "C:\Library\SDN-master\SDNExpress\scripts\SDNExpressModule.psm1" as above

**Comment by TesterTesterson1004** [comment]
While I can confirm this workaround succeeds - it is very tedious and 'dangerous' - in the sense that for a student, they must implement it precisely or be faced with failure and the likely need to restart the lab from scratch to try again if at first they fail...with all of the intendant excessively long setup-times to try again.

Short of some commits over at providing repo to help us out here, what are some thoughts to fix this independently?

Can a pre-edited version of the file be created for use here in the interim and some form of 'warning!' be added to the instructions?

**Comment by TJGitHubUser** [comment]
This has been fixed.

- Edits & updates to final portion of 4A instructions, both Student & LAK versions
- Added edited/fixed SDNExpressModule.psm1, placed in new /Allfiles dir for easy download.
